// src/parts/footer.tsx
import {Anchor, Box, Center, Container, Group, Image, Stack, Text} from "@mantine/core";
import classes from "@/app/global.module.css";
import {IconMail, IconMessageDots} from "@tabler/icons-react";
import imgSjtugText from "@/assets/sjtug.svg"

export const Footer = () => (
  <Stack bg={"var(--mantine-color-footer)"} w={"100%"} py={"xxxl"}>
    <Container className={classes.container}>
      <Group align="center" justify={"center"} gap={"xl"}>
        <Group justify={"center"} style={{flex: 3, flexWrap: "nowrap"}} miw={"min(100%, 30em)"}>
          <Box style={{flex: 1}} maw={"20em"} mb={"auto"}>
            <Image alt={"SJTUG Logo"} src={imgSjtugText} w={"100%"}/>
          </Box>
          <Stack className={classes.textNormal} gap={"xs"} style={{flex: 3}} miw={"min(100%, 15em)"}>
            <Text fw={700} inherit>SJTUG Siyuan Mirror</Text>
            <Text inherit>由 上海交通大学 Linux 用户组 (SJTUG) 维护</Text>
            <Text inherit>沪交 ICP 备 20180085</Text>
          </Stack>
        </Group>
        <Center style={{flex: 1}} miw={"min(100%, 10em)"}>
          <Stack className={classes.textNormal} gap={"xs"}>
            <Anchor href={"https://github.com/sjtug/mirror-requests"} target="_blank" c={"var(--text-color)"} inherit>
              <Group align={"center"} gap={0} wrap={"nowrap"}>
                <IconMessageDots size={24} stroke={1.5} style={{flexShrink: 0}}/>
                反馈 Bug / 提交新镜像请求
              </Group>
            </Anchor>
            <Anchor href={"mailto:sjtug-mirror-maintainers@googlegroups.com"} c={"var(--text-color)"} inherit>
              <Group align={"center"} gap={0} wrap={"nowrap"}>
                <IconMail size={24} stroke={1.5} style={{flexShrink: 0}}/>
                邮件联系镜像源管理员
              </Group>
            </Anchor>
          </Stack>
        </Center>

      </Group>
    </Container>
  </Stack>
);

// src/components/partial/footer.vue
<template>
<footer class="footer">
  <div class="container">
    <div class="columns">
      <div class="column is-9">
        软件源服务由
        <ul>
          <li>
            <a href="http://sjtug.org">
              <img src="@/assets/logo.png" class="footer-logo">上海交通大学Linux用户组 (SJTUG)
            </a>
            维护
          </li>
          <li>
            <a href="http://net.sjtu.edu.cn">上海交通大学网络信息中心</a>
            赞助资源
          </li>
		      <li>
		        沪交ICP备20180085
		      </li>
        </ul>
      </div>
      <div class="column">
        <aside class="menu">
          <ul class="menu-list">
            <li>
              <a href="https://github.com/sjtug/mirror-requests/issues/new/choose" target="_blank" rel="nofollow">
                <span class="icon">
                  <i class="fa fa-commenting-o"></i>
                </span>
                反馈Bug/提交新镜像请求
              </a>
            </li>
            <li>
              <a href="mailto:sjtug-mirror-maintainers@googlegroups.com">
                <span class="icon">
                  <i class="fa fa-envelope-o"></i>
                </span>
              给我们发送邮件
              </a>
            </li>
          </ul>
        </aside>
      </div>
    </div>
  </div>
</footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>

<style lang="scss" scoped>
.footer-logo {
  width: 1.5rem;
  vertical-align: text-bottom;
}
</style>
